task_name: AntSixLegsEnv-v0
alg: PPO
policy: GnnPolicy

device: cpu

learning_rate: 3.0e-4
total_timesteps: 1000000
n_steps: 1024
batch_size: 64
activation_fn: Tanh
xml_assets_path: NerveNet/gym_envs/assets

net_arch: 
  input:
    - [Linear, 16]
  propagate:
    - [NerveNetConv, 16]
    - [NerveNetConv, 16]
    - [NerveNetConv, 16]
  policy:
    - [Linear, 16]
  value:
    - [Linear, 16]
