task_name: AntSixLegsEnv-v0
alg: PPO
policy: MlpPolicy

device: cpu

total_timesteps: !!float 2e6
n_envs: 1

batch_size: 64
n_epochs: 10
n_steps: 4096
learning_rate: 0.0005


net_arch:
  - pi:
      - 64
      - 64
    vf:
      - 64
      - 64