#experiment_name: split_readout

task_name: AntBulletEnv-v0
alg: PPO
policy: GnnPolicy

device: cpu

drop_body_nodes: True
use_sibling_relations: True

# ["action_per_controller", "pooled", "pooled_by_group", "flattened"]
policy_readout_mode: 'action_per_controller'

gnn_for_values: False
learning_rate: 5.0e-4

total_timesteps: !!float 2e6
n_envs: 1
n_steps: 2048
batch_size: 64
activation_fn: Tanh

net_arch: 
  input:
    - [Linear, 12]
  propagate:
    - [NerveNetConv, 32]
    - [NerveNetConv, 32]
    - [NerveNetConv, 32]
    - [NerveNetConv, 32]

  policy:
    - [Linear, 32]
  value:
    - [Linear, 32]
    - [Linear, 32]

