experiment_name: 'GNN_Prop16_16_16_P16_V16_N1000_B16_lr3e-4_GNNFORvALUES'

task_name: AntBulletEnv-v0
alg: PPO
policy: GnnPolicy

device: cpu

gnn_for_values: True
learning_rate: 3.0e-4
total_timesteps: 1000000
n_steps: 1000
batch_size: 64
activation_fn: Tanh
