#experiment_name: split_readout
#experiment_name_suffix: ""
task_name: AntBulletEnv-v0
alg: PPO
policy: GnnPolicy

device: cpu

drop_body_nodes: True
use_sibling_relations: False

# ["action_per_controller", "pooled", "pooled_by_group", "flattened"]
policy_readout_mode: 'pooled_by_group'

gnn_for_values: False
learning_rate: 3.0e-4

total_timesteps: !!float 4e6
n_envs: 1
n_steps: 2048
batch_size: 64
activation_fn: Tanh

net_arch: 
  input:
    - [Linear, 12]
  propagate:
    - [NerveNetConv, 64]
    - [NerveNetConv, 64]
    - [NerveNetConv, 64]
    - [NerveNetConv, 64]
  policy:
    - [Linear, 32]
  value:
    - [Linear, 32]

