experiment_name: 'GNN_Prop64_64_64_P64_V64_N1000_B64_lr7e-5_GNNFORvALUES'

task_name: AntBulletEnv-v0
alg: PPO
policy: GnnPolicy

device: cpu

gnn_for_values: True
learning_rate: 7.0e-5
total_timesteps: 1400000
n_steps: 1000
batch_size: 64
activation_fn: Tanh

net_arch: 
  input:
    - [Linear, 12]
  propagate:
    - [NerveNetConv, 64]
    - [NerveNetConv, 64]
    - [NerveNetConv, 64]
    - [NerveNetConv, 64]
  policy:
    - [Linear, 64]
  value:
    - [Linear, 64]
