task_name: AntBulletEnv-v0
alg: PPO
policy: GnnPolicy

device: cpu

drop_body_nodes: True
use_sibling_relations: False
gnn_for_values: True
learning_rate: 1.0e-4

total_timesteps: !!float 2e6
n_envs: 1
n_steps: 1000
batch_size: 64
activation_fn: Tanh

net_arch: 
  input:
    - [Linear, 16]
  propagate:
    - [NerveNetConv, 64]
    - [NerveNetConv, 64]
    - [NerveNetConv, 64]
    - [NerveNetConv, 64]
  policy:
    - [Linear, 16]
  value:
    - [Linear, 16]
