experiment_name: 'GNN_Prop64_64_64_P64_16_V64_16_N1000_B64_lr3e-4_GNNFORvALUES'

task_name: AntBulletEnv-v0
alg: PPO
policy: GnnPolicy

device: cpu

gnn_for_values: True
learning_rate: 3.0e-4
total_timesteps: 1000000
n_steps: 1000
batch_size: 64
activation_fn: Tanh

net_arch: 
  input:
    - [Linear, 12]
  propagate:
    - [NerveNetConv, 12]
  policy:
    - [Linear, 64]
  value:
    - [Linear, 64]
