experiment_name: 'GNN_Prop16_16_16_P16_V16_N128_B64_lr3e-4'
task_name: ReacherBulletEnv-v0
alg: PPO
policy: GnnPolicy

device: cuda

learning_rate: 3.0e-5
total_timesteps: 1000000
n_steps: 128
batch_size: 64
activation_fn: Tanh