experiment_name: 'GNN_Prop12_12_12_12_P16_V16_N64_B64_lr3e-4_ReLU'

task_name: AntBulletEnv-v0
alg: PPO
policy: GnnPolicy

device: cuda

learning_rate: 3.0e-4
total_timesteps: 1000000
n_steps: 64
batch_size: 64
activation_fn: ReLU
