experiment_name: lower_lr

task_name: AntBulletEnv-v0
alg: PPO
policy: GnnPolicy

device: cpu

drop_body_nodes: True
use_sibling_relations: False
gnn_for_values: True
learning_rate: 5.0e-3

total_timesteps: !!float 2e6
n_envs: 4
n_steps: 1000
batch_size: 256
activation_fn: Tanh

net_arch: 
  input:
    - [Linear, 16]
  propagate:
    - [NerveNetConv, 32]
    - [NerveNetConv, 32]
    - [NerveNetConv, 32]
    - [NerveNetConv, 32]
  policy:
    - [Linear, 32]
  value:
    - [Linear, 32]
