experiment_name: 'GNN_Prop8_8_8_P16_V16_N512_B64_lr3e-4'

task_name: AntBulletEnv-v0
alg: PPO
policy: GnnPolicy

device: cpu

learning_rate: 3.0e-4
total_timesteps: 1000000
n_steps: 512
batch_size: 64
activation_fn: Tanh


net_arch: 
  input:
    - [Linear, 12]
  propagate:
    - [NerveNetConv, 12]
  policy:
    - [Linear, 64]
  value:
    - [Linear, 64]
