#experiment_name: split_readout
experiment_name_suffix: "GRU"
task_name: AntBulletEnv-v0
alg: PPO
policy: GnnPolicy

device: cpu

drop_body_nodes: True
use_sibling_relations: False
controller_option: unified
embedding_option: shared

# ["action_per_controller", "pooled", "pooled_by_group", "flattened"]
policy_readout_mode: 'pooled_by_group'

gnn_for_values: False
learning_rate: 2.0e-4

total_timesteps: !!float 2e6
n_envs: 4
n_steps: 2048
batch_size: 256
activation_fn: Tanh

net_arch: 
  input:
    - [Linear, 64]
  propagate:
    - [NerveNetConvGRU, [64, 32, 4]] # in/out x num_layers
  policy:
    - [Linear, 64]
  value:
    - [Linear, 64]
    - [Linear, 64]
