task_name: AntBulletEnv-v0
alg: PPO
policy: GnnPolicy

device: cpu

gnn_for_values: True
learning_rate: 3.0e-4
total_timesteps: 1300000
n_steps: 1000
batch_size: 64
activation_fn: Tanh

net_arch: 
  input:
    - [Linear, 16]
  propagate:
    - [NerveNetConv, 32]
    - [NerveNetConv, 32]
    - [NerveNetConv, 32]
  policy:
    - [Linear, 32]
  value:
    - [Linear, 32]
