experiment_name: 'GNN_Prop64_64_64_64_P16_V16_N1024_B64_lr3e-4_AntBulletEnv-v0_12-01_21-49-59'

task_name: AntBulletEnv-v0
alg: PPO
policy: GnnPolicy

device: cuda

learning_rate: 3.0e-4
total_timesteps: 1000000
n_steps: 64
batch_size: 64
activation_fn: ReLU
