#experiment_name: split_readout
#experiment_name_suffix: ""
task_name: AntBulletEnv-v0
alg: PPO
policy: GnnPolicy

device: cpu

drop_body_nodes: True
use_sibling_relations: True
gnn_for_values: True
learning_rate: 2.0e-4

total_timesteps: !!float 2e6
n_envs: 1
n_steps: 2048
batch_size: 64
activation_fn: Tanh

net_arch: 
  input:
    - [Linear, 6]
  propagate:
    - [NerveNetConv, 12]
    - [NerveNetConv, 12]
    - [NerveNetConv, 12]
    - [NerveNetConv, 12]
    - [NerveNetConv, 12]
  policy:
    - [Linear, 32]
  value:
    - [Linear, 32]
