experiment_name: 'GNNUnifiedDebug'

task_name: AntBulletEnv-v0
alg: PPO
policy: GnnPolicy

device: cpu

embedding_option: unified
learning_rate: 4.0e-3
total_timesteps: 1000000
n_steps: 1024
batch_size: 64
activation_fn: Tanh
