experiment_name: 'GNN_Prop16_B512_lr3e-4'

task_name: AntBulletEnv-v0
alg: PPO
policy: GnnPolicy

device: cuda

learning_rate: 3.0e-4
total_timesteps: 1000000
n_steps: 512
batch_size: 512
activation_fn: Tanh
