
experiment_name_suffix: "big readout"
task_name: AntBulletEnv-v0
alg: PPO
policy: GnnPolicy

device: cpu

drop_body_nodes: True
use_sibling_relations: False
gnn_for_values: True
learning_rate: 3.0e-4

total_timesteps: !!float 2e6
n_envs: 1
n_steps: 2048
batch_size: 64
activation_fn: Tanh

net_arch: 
  input:
    - [Linear, 16]
  propagate:
    - [NerveNetConv, 16]
    - [NerveNetConv, 16]
    - [NerveNetConv, 16]
    - [NerveNetConv, 16]
    - [NerveNetConv, 16]
  policy:
    - [Linear, 64]
  value:
    - [Linear, 64]
