
experiment_name_suffix: "deeper_propnet"
task_name: AntBulletEnv-v0
alg: PPO
policy: GnnPolicy

device: cpu

drop_body_nodes: False
use_sibling_relations: False
gnn_for_values: False
learning_rate: 3.0e-4

total_timesteps: !!float 1e6
n_envs: 2
n_steps: 2048
batch_size: 128
activation_fn: Tanh

net_arch: 
  input:
    - [Linear, 16]
  propagate:
    - [NerveNetConv, 16]
    - [NerveNetConv, 16]
    - [NerveNetConv, 8]
    - [NerveNetConv, 8]
  policy:
    - [Linear, 64]
  value:
    - [Linear, 64]
    - [Linear, 64]
