experiment_name: MLP_S64_P64_V64_N1000_B64_lr3e-4

task_name: AntBulletEnv-v0
alg: PPO
policy: MlpPolicy

device: cpu

learning_rate: 3.0e-4
total_timesteps: 1000000
n_steps: 1000
batch_size: 64

net_arch: 
  - 64
  - pi: [64]
    vf: [64]
